(clojure.core/let [[arg-map__36638__auto__
                    &
                    root-objects__36639__auto__] (xmlschema.core/normalize-args
                                                   [{:targetNamespace
                                                     "urn:iso:std:iso:20022:tech:xsd:sddhr:pain.002.001.03",
                                                     :xmlns:xs
                                                     "http://www.w3.org/2001/XMLSchema",
                                                     :elementFormDefault
                                                     "qualified",
                                                     :xmlns
                                                     "urn:iso:std:iso:20022:tech:xsd:sddhr:pain.002.001.03"}
                                                    (clojure.core/let 
                                                      [[arg-map__36615__auto__
                                                        type-fn__36616__auto__]
                                                       (xmlschema.core/normalize-args
                                                         [{:name
                                                           "Document",
                                                           :type
                                                           "Document"}])]
                                                      (xmlschema.core/element-fn
                                                        type-fn__36616__auto__
                                                        (clojure.core/->
                                                         arg-map__36615__auto__
                                                         :name
                                                         clojure.core/keyword)
                                                        (:ref
                                                          arg-map__36615__auto__)
                                                        (:type
                                                          arg-map__36615__auto__)
                                                        (:default
                                                          arg-map__36615__auto__)
                                                        (:fixed
                                                          arg-map__36615__auto__)))
                                                    (clojure.core/let 
                                                      [args__36759__auto__
                                                       (xmlschema.core/normalize-args
                                                         [{:name
                                                           "AccountIdentification4Choice_HR"}
                                                          (clojure.core/let 
                                                            [[arg-map__36733__auto__
                                                              &
                                                              elements__36734__auto__]
                                                             (xmlschema.core/normalize-args
                                                               [(clojure.core/let 
                                                                  [[arg-map__36615__auto__
                                                                    type-fn__36616__auto__]
                                                                   (xmlschema.core/normalize-args
                                                                     [{:name
                                                                       "Othr",
                                                                       :type
                                                                       "GenericAccountIdentification1_HR"}])]
                                                                  (xmlschema.core/element-fn
                                                                    type-fn__36616__auto__
                                                                    (clojure.core/->
                                                                     arg-map__36615__auto__
                                                                     :name
                                                                     clojure.core/keyword)
                                                                    (:ref
                                                                      arg-map__36615__auto__)
                                                                    (:type
                                                                      arg-map__36615__auto__)
                                                                    (:default
                                                                      arg-map__36615__auto__)
                                                                    (:fixed
                                                                      arg-map__36615__auto__)))])
                                                             [min-occurs__36735__auto__
                                                              max-occurs__36736__auto__]
                                                             (xmlschema.core/min-max-occurs-of
                                                               arg-map__36733__auto__)
                                                             the-map__36737__auto__
                                                             (xmlschema.core/make-map
                                                               elements__36734__auto__)]
                                                            (xmlschema.core/schema-sequence-fn
                                                              the-map__36737__auto__
                                                              min-occurs__36735__auto__
                                                              max-occurs__36736__auto__
                                                              elements__36734__auto__))])]
                                                      (xmlschema.core/complexType-fn
                                                        (:name
                                                          (clojure.core/first
                                                            args__36759__auto__))
                                                        (xmlschema.core/sub-element-of
                                                          (clojure.core/rest
                                                            args__36759__auto__))
                                                        (xmlschema.core/attrs-of
                                                          args__36759__auto__)))])
                   elements__36640__auto__ (clojure.core/filter
                                             (clojure.core/fn 
                                               [e__36641__auto__]
                                               (clojure.core/=
                                                 (:type
                                                   (clojure.core/meta
                                                     e__36641__auto__))
                                                 :element))
                                             root-objects__36639__auto__)
                   elem-map__36642__auto__ (clojure.core/apply
                                             clojure.core/merge
                                             (clojure.core/map
                                               (clojure.core/fn 
                                                 [e__36641__auto__]
                                                 {(clojure.core/->
                                                   e__36641__auto__
                                                   clojure.core/meta
                                                   :name)
                                                  e__36641__auto__})
                                               elements__36640__auto__))
                   env__36643__auto__ (clojure.core/merge
                                        xmlschema.core/env
                                        (clojure.core/apply
                                          clojure.core/merge
                                          (clojure.core/map
                                            (clojure.core/fn 
                                              [e__36641__auto__]
                                              {(xmlschema.core/name-of
                                                 e__36641__auto__)
                                               e__36641__auto__})
                                            (xmlschema.core/only-named-objects
                                              root-objects__36639__auto__))))
                   imports__36644__auto__ (clojure.core/filter
                                            #(clojure.core/=
                                              (clojure.core/->
                                               %
                                               clojure.core/meta
                                               :type)
                                              :import)
                                            root-objects__36639__auto__)
                   import-env__36646__auto__ (clojure.core/apply
                                               clojure.core/merge
                                               (clojure.core/map
                                                 #(clojure.core/->
                                                   %
                                                   clojure.core/meta
                                                   :env)
                                                 imports__36644__auto__))]
  (xmlschema.core/schema-fn
    (clojure.core/apply
      clojure.core/merge
      env__36643__auto__
      import-env__36646__auto__)
    elem-map__36642__auto__
    elements__36640__auto__
    (clojure.core/set (clojure.core/keys env__36643__auto__))
    arg-map__36638__auto__))